import { TicketIcon, TagIcon, TicketXIcon } from "lucide-react";

export interface Coupon {
  id: string;
  code: string;
  couponType: "Individual" | "Enterprise" | "School";
  module: "1-on-1 Booking" | "Workshop" | "Group Session";
  organizationName: string;
  assignedTo: string;
  assignedEmail: string;
  assignedContact: string;
  emailSent: boolean;
  emailHistory: { status: "Sent" | "Failed"; timestamp: string }[];
  redeemed: boolean;
  status: "Active" | "Used" | "Expired";
  value: number;
  utilizedAmount: number;
  balance: number;
  createdAt: string;
  validUntil: string;
  createdBy: string;
}

export interface SessionBooking {
  id: string;
  bookingId: string;
  user: string;
  userEmail: string;
  couponCode: string;
  couponId: string;
  amount: number;
  sessionName: string;
  sessionType: "1-on-1 Booking" | "Workshop" | "Group Session";
  bookingDate: string;
  bookingTime: string;
  status: "Confirmed" | "Completed" | "Cancelled" | "Upcoming";
}

export const mockCoupons: Coupon[] = [
  {
    id: "1",
    code: "POSITIVTYNESTLE2025",
    couponType: "Enterprise",
    module: "1-on-1 Booking",
    organizationName: "Nestle India",
    assignedTo: "Rajesh Kumar",
    assignedEmail: "rajesh.kumar@nestle.com",
    assignedContact: "+91 98765 43210",
    emailSent: true,
    emailHistory: [
      { status: "Sent", timestamp: "Mar 15, 2025 10:30 AM" },
    ],
    redeemed: true,
    status: "Active",
    value: 20000,
    utilizedAmount: 8500,
    balance: 11500,
    createdAt: "Mar 15, 2025",
    validUntil: "Sep 15, 2025",
    createdBy: "Admin - B2B Module",
  },
  {
    id: "2",
    code: "POSITIVTYINFOSYS100",
    couponType: "Enterprise",
    module: "1-on-1 Booking",
    organizationName: "Infosys Ltd",
    assignedTo: "Priya Sharma",
    assignedEmail: "priya.sharma@infosys.com",
    assignedContact: "+91 87654 32109",
    emailSent: true,
    emailHistory: [
      { status: "Failed", timestamp: "Feb 20, 2025 09:00 AM" },
      { status: "Sent", timestamp: "Feb 20, 2025 11:15 AM" },
    ],
    redeemed: true,
    status: "Active",
    value: 50000,
    utilizedAmount: 32000,
    balance: 18000,
    createdAt: "Feb 20, 2025",
    validUntil: "Aug 20, 2025",
    createdBy: "Admin - B2B Module",
  },
  {
    id: "3",
    code: "POSITIVTYTCS500",
    couponType: "Enterprise",
    module: "1-on-1 Booking",
    organizationName: "TCS",
    assignedTo: "Amit Patel",
    assignedEmail: "amit.patel@tcs.com",
    assignedContact: "+91 76543 21098",
    emailSent: true,
    emailHistory: [
      { status: "Sent", timestamp: "Jan 10, 2025 08:00 AM" },
    ],
    redeemed: true,
    status: "Used",
    value: 15000,
    utilizedAmount: 15000,
    balance: 0,
    createdAt: "Jan 10, 2025",
    validUntil: "Apr 10, 2025",
    createdBy: "Admin - B2B Module",
  },
  {
    id: "4",
    code: "POSITIVTYIITD2025",
    couponType: "School",
    module: "Group Session",
    organizationName: "IIT Delhi",
    assignedTo: "Dr. Neha Gupta",
    assignedEmail: "neha.gupta@iitd.ac.in",
    assignedContact: "+91 65432 10987",
    emailSent: true,
    emailHistory: [
      { status: "Sent", timestamp: "Mar 01, 2025 02:00 PM" },
    ],
    redeemed: true,
    status: "Active",
    value: 30000,
    utilizedAmount: 12000,
    balance: 18000,
    createdAt: "Mar 01, 2025",
    validUntil: "Dec 31, 2025",
    createdBy: "Admin - B2B Module",
  },
  {
    id: "5",
    code: "POSITIVTYLOV123",
    couponType: "Individual",
    module: "1-on-1 Booking",
    organizationName: "—",
    assignedTo: "Sneha Reddy",
    assignedEmail: "sneha.reddy@gmail.com",
    assignedContact: "+91 54321 09876",
    emailSent: true,
    emailHistory: [
      { status: "Sent", timestamp: "Mar 20, 2025 04:00 PM" },
    ],
    redeemed: false,
    status: "Active",
    value: 5000,
    utilizedAmount: 0,
    balance: 5000,
    createdAt: "Mar 20, 2025",
    validUntil: "Jun 20, 2025",
    createdBy: "Admin - Individual Module",
  },
  {
    id: "6",
    code: "POSITIVTYWIPRO25",
    couponType: "Enterprise",
    module: "Workshop",
    organizationName: "Wipro Technologies",
    assignedTo: "Vikram Singh",
    assignedEmail: "vikram.singh@wipro.com",
    assignedContact: "+91 43210 98765",
    emailSent: false,
    emailHistory: [
      { status: "Failed", timestamp: "Mar 25, 2025 10:00 AM" },
    ],
    redeemed: false,
    status: "Active",
    value: 25000,
    utilizedAmount: 0,
    balance: 25000,
    createdAt: "Mar 25, 2025",
    validUntil: "Sep 25, 2025",
    createdBy: "Admin - B2B Module",
  },
  {
    id: "7",
    code: "POSITIVTYDPS2025",
    couponType: "School",
    module: "1-on-1 Booking",
    organizationName: "Delhi Public School",
    assignedTo: "Anita Verma",
    assignedEmail: "anita.verma@dps.edu.in",
    assignedContact: "+91 32109 87654",
    emailSent: true,
    emailHistory: [
      { status: "Sent", timestamp: "Feb 10, 2025 09:30 AM" },
    ],
    redeemed: true,
    status: "Expired",
    value: 10000,
    utilizedAmount: 4500,
    balance: 5500,
    createdAt: "Feb 10, 2025",
    validUntil: "Mar 10, 2025",
    createdBy: "Admin - B2B Module",
  },
  {
    id: "8",
    code: "POSITIVTYRELIANCE50",
    couponType: "Enterprise",
    module: "1-on-1 Booking",
    organizationName: "Reliance Industries",
    assignedTo: "Deepak Joshi",
    assignedEmail: "deepak.joshi@ril.com",
    assignedContact: "+91 21098 76543",
    emailSent: true,
    emailHistory: [
      { status: "Sent", timestamp: "Mar 28, 2025 11:00 AM" },
    ],
    redeemed: false,
    status: "Active",
    value: 100000,
    utilizedAmount: 0,
    balance: 100000,
    createdAt: "Mar 28, 2025",
    validUntil: "Mar 28, 2026",
    createdBy: "Admin - B2B Module",
  },
];

export const mockSessionBookings: SessionBooking[] = [
  {
    id: "s1",
    bookingId: "BK-10001",
    user: "Rahul Mehta (Nestle)",
    userEmail: "rahul.mehta@nestle.com",
    couponCode: "POSITIVTYNESTLE2025",
    couponId: "1",
    amount: 2500,
    sessionName: "Career Coaching with Dr. Ananya",
    sessionType: "1-on-1 Booking",
    bookingDate: "Mar 20, 2025",
    bookingTime: "10:00 AM",
    status: "Completed",
  },
  {
    id: "s2",
    bookingId: "BK-10002",
    user: "Sunita Rao (Nestle)",
    userEmail: "sunita.rao@nestle.com",
    couponCode: "POSITIVTYNESTLE2025",
    couponId: "1",
    amount: 3000,
    sessionName: "Stress Management Session",
    sessionType: "1-on-1 Booking",
    bookingDate: "Mar 22, 2025",
    bookingTime: "02:00 PM",
    status: "Completed",
  },
  {
    id: "s3",
    bookingId: "BK-10003",
    user: "Karan Singh (Nestle)",
    userEmail: "karan.singh@nestle.com",
    couponCode: "POSITIVTYNESTLE2025",
    couponId: "1",
    amount: 3000,
    sessionName: "Leadership Coaching",
    sessionType: "1-on-1 Booking",
    bookingDate: "Mar 25, 2025",
    bookingTime: "11:00 AM",
    status: "Confirmed",
  },
  {
    id: "s4",
    bookingId: "BK-10004",
    user: "Meena Iyer (Infosys)",
    userEmail: "meena.iyer@infosys.com",
    couponCode: "POSITIVTYINFOSYS100",
    couponId: "2",
    amount: 2500,
    sessionName: "Work-Life Balance Workshop",
    sessionType: "1-on-1 Booking",
    bookingDate: "Mar 18, 2025",
    bookingTime: "03:00 PM",
    status: "Completed",
  },
  {
    id: "s5",
    bookingId: "BK-10005",
    user: "Arjun Nair (Infosys)",
    userEmail: "arjun.nair@infosys.com",
    couponCode: "POSITIVTYINFOSYS100",
    couponId: "2",
    amount: 5000,
    sessionName: "Executive Wellness Program",
    sessionType: "1-on-1 Booking",
    bookingDate: "Mar 20, 2025",
    bookingTime: "09:00 AM",
    status: "Completed",
  },
  {
    id: "s6",
    bookingId: "BK-10006",
    user: "Sanjay Kumar (Infosys)",
    userEmail: "sanjay.kumar@infosys.com",
    couponCode: "POSITIVTYINFOSYS100",
    couponId: "2",
    amount: 4500,
    sessionName: "Mindfulness & Meditation",
    sessionType: "1-on-1 Booking",
    bookingDate: "Mar 24, 2025",
    bookingTime: "04:00 PM",
    status: "Upcoming",
  },
  {
    id: "s7",
    bookingId: "BK-10007",
    user: "Ravi Teja (TCS)",
    userEmail: "ravi.teja@tcs.com",
    couponCode: "POSITIVTYTCS500",
    couponId: "3",
    amount: 7500,
    sessionName: "Burnout Recovery Program",
    sessionType: "1-on-1 Booking",
    bookingDate: "Feb 15, 2025",
    bookingTime: "10:00 AM",
    status: "Completed",
  },
  {
    id: "s8",
    bookingId: "BK-10008",
    user: "Pooja Desai (TCS)",
    userEmail: "pooja.desai@tcs.com",
    couponCode: "POSITIVTYTCS500",
    couponId: "3",
    amount: 7500,
    sessionName: "Emotional Intelligence Training",
    sessionType: "1-on-1 Booking",
    bookingDate: "Mar 01, 2025",
    bookingTime: "11:30 AM",
    status: "Completed",
  },
  {
    id: "s9",
    bookingId: "BK-10009",
    user: "IIT Delhi - Batch A",
    userEmail: "counseling@iitd.ac.in",
    couponCode: "POSITIVTYIITD2025",
    couponId: "4",
    amount: 6000,
    sessionName: "Student Wellness Group Session",
    sessionType: "Group Session",
    bookingDate: "Mar 10, 2025",
    bookingTime: "02:00 PM",
    status: "Completed",
  },
  {
    id: "s10",
    bookingId: "BK-10010",
    user: "IIT Delhi - Batch B",
    userEmail: "counseling@iitd.ac.in",
    couponCode: "POSITIVTYIITD2025",
    couponId: "4",
    amount: 6000,
    sessionName: "Exam Anxiety Management",
    sessionType: "Group Session",
    bookingDate: "Mar 20, 2025",
    bookingTime: "03:00 PM",
    status: "Upcoming",
  },
  {
    id: "s11",
    bookingId: "BK-10011",
    user: "DPS Students - Grade 12",
    userEmail: "anita.verma@dps.edu.in",
    couponCode: "POSITIVTYDPS2025",
    couponId: "7",
    amount: 4500,
    sessionName: "Board Exam Stress Relief",
    sessionType: "1-on-1 Booking",
    bookingDate: "Feb 20, 2025",
    bookingTime: "01:00 PM",
    status: "Completed",
  },
];

export const mockChartData = [
  { date: "Mar 16", redeemed: 8, expired: 1, created: 3 },
  { date: "Mar 17", redeemed: 12, expired: 0, created: 2 },
  { date: "Mar 18", redeemed: 15, expired: 2, created: 5 },
  { date: "Mar 19", redeemed: 10, expired: 0, created: 1 },
  { date: "Mar 20", redeemed: 18, expired: 1, created: 4 },
  { date: "Mar 21", redeemed: 14, expired: 0, created: 2 },
  { date: "Mar 22", redeemed: 20, expired: 3, created: 6 },
];

export const mockRecentActivity = [
  {
    id: "a1",
    type: "redemption",
    icon: TicketIcon,
    message: "Session booked via coupon",
    couponCode: "POSITIVTYNESTLE2025",
    time: "2 minutes ago",
    user: "karan.singh@nestle.com",
    amount: "₹3,000",
    module: "1-on-1 Booking",
    bookingId: "BK-10003",
  },
  {
    id: "a2",
    type: "creation",
    icon: TagIcon,
    message: "Enterprise coupon created",
    couponCode: "POSITIVTYRELIANCE50",
    time: "1 hour ago",
    user: "admin@positvity.com",
    module: "Enterprise",
    emailStatus: "Sent" as const,
  },
  {
    id: "a3",
    type: "redemption",
    icon: TicketIcon,
    message: "Session booked via coupon",
    couponCode: "POSITIVTYINFOSYS100",
    time: "3 hours ago",
    user: "sanjay.kumar@infosys.com",
    amount: "₹4,500",
    module: "1-on-1 Booking",
    bookingId: "BK-10006",
  },
  {
    id: "a4",
    type: "expiration",
    icon: TicketXIcon,
    message: "Coupon expired",
    couponCode: "POSITIVTYDPS2025",
    time: "5 hours ago",
    user: "system",
    module: "School",
  },
  {
    id: "a5",
    type: "redemption",
    icon: TicketIcon,
    message: "Group session booked",
    couponCode: "POSITIVTYIITD2025",
    time: "1 day ago",
    user: "counseling@iitd.ac.in",
    amount: "₹6,000",
    module: "Group Session",
    bookingId: "BK-10010",
  },
  {
    id: "a6",
    type: "creation",
    icon: TagIcon,
    message: "Email delivery failed",
    couponCode: "POSITIVTYWIPRO25",
    time: "2 days ago",
    user: "admin@positvity.com",
    module: "Enterprise",
    emailStatus: "Failed" as const,
  },
];
